---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

# Install dependencies on the host
- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip', ]
    state: latest
    update_cache: yes

- name: Add R apt repository
  apt_repository:
    repo: "ppa:marutter/rrutter4.0"
    state: present

- name: Install R and dependencies
  apt:
    name:
      - r-base
      - r-base-dev
      - libxml2-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libssh2-1-dev
    state: present